-- MySQL Script generated by MySQL Workbench
-- 05/05/15 12:29:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema alarmas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema alarmas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `alarmas` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `alarmas` ;

-- -----------------------------------------------------
-- Table `alarmas`.`personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alarmas`.`personas` (
  `persona_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Identificador de la tabla Personas',
  `nombre_persona` CHAR(128) NULL COMMENT 'Nombre de la persona.',
  `apellido` CHAR(128) NOT NULL COMMENT 'Apellido de la persona.',
  `direccion` CHAR(128) NULL COMMENT 'Direccion de la persona.',
  `telefono_fijo` CHAR(128) NULL COMMENT 'Telefono Fijo',
  `telefono_celular` CHAR(128) NULL COMMENT 'Telefono Celular',
  `dni` INT(11) UNSIGNED NOT NULL COMMENT 'Documento Nacional de Identidad',
  `email` CHAR(128) NOT NULL COMMENT 'Email de la persona',
  `telefono_alt` CHAR(128) NULL COMMENT 'Telefono Alternativo de la Persona',
  `usuario` CHAR(128) NULL,
  `contrasena` CHAR(128) NOT NULL,
  PRIMARY KEY (`persona_id`),
  INDEX `Personas_apellido` (`apellido` ASC),
  INDEX `Personas_dni` (`dni` ASC),
  INDEX `Personas_nombre` (`nombre_persona` ASC),
  INDEX `Personas_usuario` (`usuario` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC))
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `alarmas`.`tipos_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alarmas`.`tipos_cliente` (
  `tipo_cliente_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Identificador de la tabla Tipos_Cliente. ',
  `nombre_tipo_cliente` CHAR(128) NOT NULL COMMENT 'Nombre del tipo de Cliente. ',
  `observaciones_tipo_cliente` LONGTEXT NULL COMMENT 'Observaciones.',
  PRIMARY KEY (`tipo_cliente_id`))
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `alarmas`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alarmas`.`clientes` (
  `cliente_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Identificador de la tabla Cliente.',
  `tipos_cliente_tipo_cliente_id` INT(11) UNSIGNED NOT NULL COMMENT 'Fk que hace referencia a la tabla Tipos_Cliente.',
  `personas_persona_id` INT(11) UNSIGNED NOT NULL COMMENT 'Fk que hace referencia a la tabla Personas. ',
  `direccion_cobro` CHAR(128) NULL COMMENT 'Direccion donde se le cobra a cada Cliente. ',
  `sistema_secundario_id` INT(11) UNSIGNED NULL COMMENT 'Identificador del sistema secundario que posee alarmas 911. ',
  `factura` CHAR(128) NULL COMMENT 'Tipo de Factura.',
  `razon_social` CHAR(128) NULL COMMENT 'Razon Social.',
  `cuit` INT(11) UNSIGNED NULL COMMENT 'Cuit. ',
  PRIMARY KEY (`cliente_id`),
  INDEX `Clientes_FKIndex1` (`personas_persona_id` ASC),
  INDEX `Clientes_FKIndex2` (`tipos_cliente_tipo_cliente_id` ASC),
  CONSTRAINT `fk_{A60BC66F-161C-4FDC-930F-00EFE014B693}`
    FOREIGN KEY (`personas_persona_id`)
    REFERENCES `alarmas`.`personas` (`persona_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_{5D746555-D8D9-4E0E-92C5-7E4B70A45DE3}`
    FOREIGN KEY (`tipos_cliente_tipo_cliente_id`)
    REFERENCES `alarmas`.`tipos_cliente` (`tipo_cliente_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
COMMENT = 'Tabla que describe los clientes. '
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `alarmas`.`tipos_monitoreo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alarmas`.`tipos_monitoreo` (
  `tipo_monitoreo_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Identificador de la tabla Tipos_Monitoreo',
  `nombre_tipo_monitoreo` CHAR(128) NOT NULL COMMENT 'Nombre del tipo de monitoreo. ',
  `valor` INT(11) UNSIGNED NULL COMMENT 'Valor monetario del servicio. ',
  PRIMARY KEY (`tipo_monitoreo_id`))
COMMENT = 'Tabla que representa los tipos de monitoreo que provee la empresa. '
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `alarmas`.`barrios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alarmas`.`barrios` (
  `barrio_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Identificador de la tabla Barrio. ',
  `nombre_barrio` CHAR(128) NOT NULL COMMENT 'Nombre del Barrio.',
  `observaciones_barrio` LONGTEXT NULL COMMENT 'Observaciones. ',
  PRIMARY KEY (`barrio_id`),
  INDEX `Barrios_nombre` (`nombre_barrio` ASC))
COMMENT = 'Tabla que describe los barrios.'
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `alarmas`.`marcas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alarmas`.`marcas` (
  `id_marca` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_marca` CHAR(128) NULL,
  `observaciones_marca` LONGTEXT NULL,
  PRIMARY KEY (`id_marca`),
  INDEX `Marcas_nombre` (`nombre_marca` ASC))
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `alarmas`.`modelos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alarmas`.`modelos` (
  `id_modelo` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `marcas_id_marca` INT(11) UNSIGNED NOT NULL,
  `nombre_modelo` CHAR(128) NOT NULL,
  `observaciones_modelo` LONGTEXT NULL,
  `discriminante` CHAR(128) NOT NULL,
  PRIMARY KEY (`id_modelo`),
  INDEX `Modelos_FKIndex1` (`marcas_id_marca` ASC),
  INDEX `Modelos_nombre` (`nombre_modelo` ASC),
  CONSTRAINT `fk_{233C974E-7211-4331-95CB-4835BD0F888B}`
    FOREIGN KEY (`marcas_id_marca`)
    REFERENCES `alarmas`.`marcas` (`id_marca`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `alarmas`.`sistema_alarmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alarmas`.`sistema_alarmas` (
  `sistema_alarma_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Identificador de la tabla Sistema_Alarmas',
  `nombre_sistema_alarma` CHAR(128) NOT NULL COMMENT 'Describe el nombre que posee el sistema de alarmas. Necesario para poder diferenciarlos en algunos aspectos',
  `observaciones_sistema_alarma` CHAR(128) NULL COMMENT 'Observaciones, Informacion agregada.',
  `modelos_id_modelo` INT(11) UNSIGNED NOT NULL,
  `barrios_barrio_id` INT(11) UNSIGNED NOT NULL COMMENT 'FK que hace referencia a Barrios',
  `tipos_monitoreo_tipo_monitoreo_id` INT(11) UNSIGNED NOT NULL COMMENT 'FK que hace referencia a Tipos_Monitoreo',
  `clientes_cliente_id` INT(11) UNSIGNED NOT NULL COMMENT 'FK que hace referencia a Cliente',
  PRIMARY KEY (`sistema_alarma_id`),
  INDEX `Sistema_Alarmas_FKIndex1` (`clientes_cliente_id` ASC),
  INDEX `Sistema_Alarmas_FKIndex2` (`tipos_monitoreo_tipo_monitoreo_id` ASC),
  INDEX `Sistema_Alarmas_FKIndex5` (`barrios_barrio_id` ASC),
  INDEX `Sistema_Alarmas_FKIndex6` (`modelos_id_modelo` ASC),
  INDEX `Sistema_Alarmas_nombre_sistema_alarmas` (`nombre_sistema_alarma` ASC),
  CONSTRAINT `fk_{65D24388-7E42-4323-91DD-CDBDD2A2C3F1}`
    FOREIGN KEY (`clientes_cliente_id`)
    REFERENCES `alarmas`.`clientes` (`cliente_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_{D8EAB0A6-4E62-4BE9-89C5-DC6EB1C23939}`
    FOREIGN KEY (`tipos_monitoreo_tipo_monitoreo_id`)
    REFERENCES `alarmas`.`tipos_monitoreo` (`tipo_monitoreo_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_{50921D8E-B05E-479E-827C-FE12A375116A}`
    FOREIGN KEY (`barrios_barrio_id`)
    REFERENCES `alarmas`.`barrios` (`barrio_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_{897F8BA1-E539-4AC2-AC75-7BBB3C0483AB}`
    FOREIGN KEY (`modelos_id_modelo`)
    REFERENCES `alarmas`.`modelos` (`id_modelo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
COMMENT = 'Sistemas de alarmas. \nSe refiere a la central de alarmas, al controlador. Un sistema de alarmas esta formado por mas componentes. '
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `alarmas`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alarmas`.`empleados` (
  `empleado_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'identificador de la tabla Empleados',
  `personas_persona_id` INT(11) UNSIGNED NOT NULL COMMENT 'Fk a tabla Personas',
  `funcion` CHAR(128) NULL COMMENT 'Funcion que cumple dentro de la empresa.',
  `temporal` TINYINT(1) NULL COMMENT 'Atributo Boleano que muestra si un empleado es Temporal o no. ',
  `activo` TINYINT(1) NULL COMMENT 'Atributo Boleano que describe si un empleado se encuentra tabajando en la empresa.',
  PRIMARY KEY (`empleado_id`),
  INDEX `Empleados_FKIndex1` (`personas_persona_id` ASC),
  CONSTRAINT `fk_{5ACEE372-5482-4E61-B8C8-E869528AE2C4}`
    FOREIGN KEY (`personas_persona_id`)
    REFERENCES `alarmas`.`personas` (`persona_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `alarmas`.`tipos_baterias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alarmas`.`tipos_baterias` (
  `tipo_bateria_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Identificador de la tabla Tipos_Baterias.',
  `nombre` CHAR(128) NOT NULL COMMENT 'nombre del tipo de bateria.',
  `observaciones` LONGTEXT NULL COMMENT 'Observaciones sobre el tipo de baterias.',
  PRIMARY KEY (`tipo_bateria_id`))
COMMENT = 'Tabla que describe los diferentes tipos de baterias. '
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `alarmas`.`baterias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alarmas`.`baterias` (
  `bateria_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Identificador de la tabla Baterias',
  `sistema_alarmas_sistema_alarma_id` INT(11) UNSIGNED NOT NULL,
  `modelos_id_modelo` INT(11) UNSIGNED NOT NULL,
  `tipos_baterias_tipo_bateria_id` INT(11) UNSIGNED NOT NULL COMMENT 'Fk que hace referencia a la tabla Tipos_Baterias',
  `observaciones_bateria` CHAR(128) NULL COMMENT 'Observaciones sobre la Bateria.',
  `vida_util` INT(11) UNSIGNED NULL COMMENT 'Vida Util de la bateria, descripta en meses',
  `fecha_alta` DATE NULL,
  `fecha_baja` DATE NULL,
  PRIMARY KEY (`bateria_id`),
  INDEX `Baterias_FKIndex1` (`tipos_baterias_tipo_bateria_id` ASC),
  INDEX `Baterias_FKIndex2` (`modelos_id_modelo` ASC),
  INDEX `Baterias_FKIndex3` (`sistema_alarmas_sistema_alarma_id` ASC),
  CONSTRAINT `fk_{39A4FA76-68F7-450E-B7FD-F56E019667F2}`
    FOREIGN KEY (`tipos_baterias_tipo_bateria_id`)
    REFERENCES `alarmas`.`tipos_baterias` (`tipo_bateria_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_{3A7156BF-5444-4B6D-9C3A-4DC65F450E48}`
    FOREIGN KEY (`modelos_id_modelo`)
    REFERENCES `alarmas`.`modelos` (`id_modelo`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_{FBFF92E3-E8AB-451E-8169-33390C4291A5}`
    FOREIGN KEY (`sistema_alarmas_sistema_alarma_id`)
    REFERENCES `alarmas`.`sistema_alarmas` (`sistema_alarma_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
COMMENT = 'Tabla que describe a las Baterias. '
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `alarmas`.`paneles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alarmas`.`paneles` (
  `panel_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Identificador de la tabla Paneles',
  `modelos_id_modelo` INT(11) UNSIGNED NULL,
  `baterias_bateria_id` INT(11) UNSIGNED NULL COMMENT 'Fk que hace referencia a la tabla Baterias',
  `sistema_alarmas_sistema_alarma_id` INT(11) UNSIGNED NOT NULL COMMENT 'FK que hace referencia a la tabla Sistema_Alarmas.',
  `observaciones_panel` LONGTEXT NULL COMMENT 'Observaciones',
  `nombre_panel` CHAR(128) NOT NULL,
  PRIMARY KEY (`panel_id`),
  INDEX `Paneles_FKIndex1` (`sistema_alarmas_sistema_alarma_id` ASC),
  INDEX `Paneles_FKIndex2` (`baterias_bateria_id` ASC),
  INDEX `Paneles_FKIndex3` (`modelos_id_modelo` ASC),
  CONSTRAINT `fk_{E7F0B3C2-40DB-4BBA-9DB1-19BED8B10D7C}`
    FOREIGN KEY (`sistema_alarmas_sistema_alarma_id`)
    REFERENCES `alarmas`.`sistema_alarmas` (`sistema_alarma_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_{9806A91B-9A58-4B98-9604-905C9FE0F735}`
    FOREIGN KEY (`baterias_bateria_id`)
    REFERENCES `alarmas`.`baterias` (`bateria_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_{981BB41E-5AAB-46D5-B3BE-C0BB8750BAE7}`
    FOREIGN KEY (`modelos_id_modelo`)
    REFERENCES `alarmas`.`modelos` (`id_modelo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
COMMENT = 'Tabla que describe los paneles de las alarmas. '
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `alarmas`.`accesorios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alarmas`.`accesorios` (
  `accesorio_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Identificador de la tabla Accesorios. ',
  `modelos_id_modelo` INT(11) UNSIGNED NULL,
  `baterias_bateria_id` INT(11) UNSIGNED NULL COMMENT 'Fk que hace referencia a la tabla Baterias.',
  `sistema_alarmas_sistema_alarma_id` INT(11) UNSIGNED NOT NULL COMMENT 'Fk que hace referencia a la tabla Sistema_Alarmas.',
  `nombre_accesorio` CHAR(128) NOT NULL COMMENT 'Nombre del accesorio. ',
  `observaciones_accesorio` LONGTEXT NULL COMMENT 'Observaciones. ',
  PRIMARY KEY (`accesorio_id`),
  INDEX `Accesorios_FKIndex1` (`sistema_alarmas_sistema_alarma_id` ASC),
  INDEX `Accesorios_FKIndex2` (`baterias_bateria_id` ASC),
  INDEX `Accesorios_FKIndex3` (`modelos_id_modelo` ASC),
  CONSTRAINT `fk_{E24A1639-8C2D-42F8-917F-355F7B3F1406}`
    FOREIGN KEY (`sistema_alarmas_sistema_alarma_id`)
    REFERENCES `alarmas`.`sistema_alarmas` (`sistema_alarma_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_{B576A187-CEDF-4EFC-B2FD-027E4A1AB9C1}`
    FOREIGN KEY (`baterias_bateria_id`)
    REFERENCES `alarmas`.`baterias` (`bateria_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_{E50A7048-9220-48C2-AB8C-35576BC1ADFF}`
    FOREIGN KEY (`modelos_id_modelo`)
    REFERENCES `alarmas`.`modelos` (`id_modelo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `alarmas`.`zonas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alarmas`.`zonas` (
  `zona_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'identificador de la tabla Zonas.',
  `sistema_alarmas_sistema_alarma_id` INT(11) UNSIGNED NOT NULL COMMENT 'Fk que hace referencia a la tabla Sistema_Alarmas',
  `nombre_zona` CHAR(128) NOT NULL COMMENT 'Nombre de la zona.',
  `observaciones_zona` LONGTEXT NULL COMMENT 'Observaciones',
  PRIMARY KEY (`zona_id`),
  INDEX `Zonas_FKIndex1` (`sistema_alarmas_sistema_alarma_id` ASC),
  CONSTRAINT `fk_{6A5C68BC-5DF6-4117-9CA7-5FE7994CF0EC}`
    FOREIGN KEY (`sistema_alarmas_sistema_alarma_id`)
    REFERENCES `alarmas`.`sistema_alarmas` (`sistema_alarma_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `alarmas`.`tipos_sensores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alarmas`.`tipos_sensores` (
  `tipo_sensor_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Identificador de la tabla Tipo_Sensores.',
  `nombre_sensor` CHAR(128) NOT NULL COMMENT 'Nombre del Tipo de sensor. ',
  `observaciones_sensor` LONGTEXT NULL COMMENT 'Observaciones. ',
  PRIMARY KEY (`tipo_sensor_id`))
COMMENT = 'Tabla que describe los diferentes tipos de sensores. '
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `alarmas`.`sensores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alarmas`.`sensores` (
  `sensor_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Identificador de la tabla Sensores.',
  `modelos_id_modelo` INT(11) UNSIGNED NULL,
  `baterias_bateria_id` INT(11) UNSIGNED NULL COMMENT 'Fk que hace referencia a la tabla Baterias',
  `tipos_sensores_tipo_sensor_id` INT(11) UNSIGNED NOT NULL COMMENT 'Fk que hace referencia a la tabla Tipo_Sensores. ',
  `zonas_zona_id` INT(11) UNSIGNED NOT NULL COMMENT 'Fk que hace referencia a la tabla Zonas.',
  PRIMARY KEY (`sensor_id`),
  INDEX `Sensores_FKIndex1` (`zonas_zona_id` ASC),
  INDEX `Sensores_FKIndex2` (`tipos_sensores_tipo_sensor_id` ASC),
  INDEX `Sensores_FKIndex3` (`baterias_bateria_id` ASC),
  INDEX `Sensores_FKIndex4` (`modelos_id_modelo` ASC),
  CONSTRAINT `fk_{A75BC219-0BF5-4D24-BE33-0F7DAFAF7105}`
    FOREIGN KEY (`zonas_zona_id`)
    REFERENCES `alarmas`.`zonas` (`zona_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_{066B2417-C731-4057-8852-7153B47A2296}`
    FOREIGN KEY (`tipos_sensores_tipo_sensor_id`)
    REFERENCES `alarmas`.`tipos_sensores` (`tipo_sensor_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_{594C5082-BDA3-44E7-BEB4-06CEE457D551}`
    FOREIGN KEY (`baterias_bateria_id`)
    REFERENCES `alarmas`.`baterias` (`bateria_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_{E8D7DF2B-5F1A-4FDA-B784-FA3E302A950E}`
    FOREIGN KEY (`modelos_id_modelo`)
    REFERENCES `alarmas`.`modelos` (`id_modelo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
COMMENT = 'Tabla que describe los sensores. '
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `alarmas`.`tipos_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alarmas`.`tipos_pago` (
  `tipo_pago_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'identificador de la tabla Tipos_Pago.',
  `nombre_tipo_pago` CHAR(128) NOT NULL COMMENT 'Nombre del tipo de pago. ',
  `observaciones_tipo_pago` LONGTEXT NULL COMMENT 'Observaciones. ',
  PRIMARY KEY (`tipo_pago_id`))
COMMENT = 'Tabla que describe los diferentes tipos de pago.'
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `alarmas`.`ordenes_servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alarmas`.`ordenes_servicio` (
  `orden_servicio_id` INT(11) UNSIGNED NOT NULL COMMENT 'Identificador de las Ordenes de Servicio. ',
  `sistema_alarmas_sistema_alarma_id` INT(11) UNSIGNED NOT NULL,
  `fecha_emision` DATE NOT NULL COMMENT 'Fecha en la que se emite la Orden de Servicio.',
  `fecha_cierre` DATE NOT NULL COMMENT 'Fecha en que la orden de Servicio se realizo. ',
  `importe` FLOAT NULL COMMENT 'importe.',
  `observaciones_orden_servicio` CHAR(128) NULL COMMENT 'Anotaciones u observaciones que tienen que ver con la orden de servicio. ',
  `prioridad` INT(11) UNSIGNED NULL COMMENT 'Prioridad de la orden de servicio. ',
  `vencimiento_orden` CHAR(128) NULL COMMENT 'fecha de vencimiento de la orden -  limite para el pago del servicio. ',
  PRIMARY KEY (`orden_servicio_id`),
  INDEX `Ordenes_Servicio_FKIndex2` (`sistema_alarmas_sistema_alarma_id` ASC),
  CONSTRAINT `fk_{8B252882-5D05-4531-A949-308E456558D4}`
    FOREIGN KEY (`sistema_alarmas_sistema_alarma_id`)
    REFERENCES `alarmas`.`sistema_alarmas` (`sistema_alarma_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = 'Tabla que representa las ordenes de servicio que se realizan. \nLas mismas estan relacionadas con los tipos de servicio que provee la empresa. \n'
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `alarmas`.`pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alarmas`.`pagos` (
  `pago_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Identificador de  de la tabla Pagos. ',
  `ordenes_servicio_orden_servicio_id` INT(11) UNSIGNED NOT NULL,
  `tipos_pago_tipo_pago_id` INT(11) UNSIGNED NOT NULL COMMENT 'Fk que hace referencia a la tabla Tipos_Pago',
  `importe` FLOAT NULL COMMENT 'Importe. ',
  `informacion_pago` CHAR(128) NULL COMMENT 'Utilizado para cargar informacion en un pago. Por ejemplo: El numero de factura que se pago. ',
  PRIMARY KEY (`pago_id`),
  INDEX `Pagos_FKIndex1` (`tipos_pago_tipo_pago_id` ASC),
  INDEX `Pagos_FKIndex2` (`ordenes_servicio_orden_servicio_id` ASC),
  CONSTRAINT `fk_{A3ABD81F-10DC-42BA-BA9A-C82DD8A7D021}`
    FOREIGN KEY (`tipos_pago_tipo_pago_id`)
    REFERENCES `alarmas`.`tipos_pago` (`tipo_pago_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_{D667C00C-4620-4D16-AC56-9CA44D08D7E9}`
    FOREIGN KEY (`ordenes_servicio_orden_servicio_id`)
    REFERENCES `alarmas`.`ordenes_servicio` (`orden_servicio_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `alarmas`.`clientes_pagos_fecha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alarmas`.`clientes_pagos_fecha` (
  `cliente_pago_fecha_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Identificador de la tabla Cliente_Pagos_Fecha',
  `pagos_pago_id` INT(11) UNSIGNED NULL COMMENT 'Fk que hace referencia a la tabla Pagos',
  `clientes_cliente_id` INT(11) UNSIGNED NULL COMMENT 'Fk que hace referencia a la tabla Cliente',
  `fecha` DATE NULL COMMENT 'Fecha',
  PRIMARY KEY (`cliente_pago_fecha_id`),
  INDEX `Clientes_Pagos_Fecha_FKIndex1` (`clientes_cliente_id` ASC),
  INDEX `Clientes_Pagos_Fecha_FKIndex2` (`pagos_pago_id` ASC),
  CONSTRAINT `fk_{DF8689B8-02D9-4CE1-9541-901B5E6118B5}`
    FOREIGN KEY (`clientes_cliente_id`)
    REFERENCES `alarmas`.`clientes` (`cliente_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_{86A81C84-A6B3-4E37-AB21-A81736EBE1AE}`
    FOREIGN KEY (`pagos_pago_id`)
    REFERENCES `alarmas`.`pagos` (`pago_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
COMMENT = 'Tabla resultante de la relacion N a N de las tablas Pagos y Clientes.'
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `alarmas`.`empleados_has_ordenes_servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alarmas`.`empleados_has_ordenes_servicio` (
  `empleados_empleado_id` INT(11) UNSIGNED NOT NULL COMMENT 'FK que referencia la tabla de Empleados.',
  `ordenes_servicio_orden_servicio_id` INT(11) UNSIGNED NOT NULL COMMENT 'FK que referencia la tabla Ordenes de Servicio.',
  `fecha` DATE NULL COMMENT 'Fecha en la que se emite una orden de servicio y el/los empleados que la realizan',
  PRIMARY KEY (`empleados_empleado_id`, `ordenes_servicio_orden_servicio_id`),
  INDEX `Empleados_has_Ordenes_Servicio_FKIndex1` (`empleados_empleado_id` ASC),
  INDEX `Empleados_has_Ordenes_Servicio_FKIndex2` (`ordenes_servicio_orden_servicio_id` ASC),
  CONSTRAINT `fk_{1EC8B08F-563E-4AF3-8D3C-F8F694B5E6F4}`
    FOREIGN KEY (`empleados_empleado_id`)
    REFERENCES `alarmas`.`empleados` (`empleado_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_{943A457E-0896-4EB1-9106-BC209DECF625}`
    FOREIGN KEY (`ordenes_servicio_orden_servicio_id`)
    REFERENCES `alarmas`.`ordenes_servicio` (`orden_servicio_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
COMMENT = 'Tabla resultante entre la relacion N a N de empleados y Ordenes de Servicio'
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `alarmas`.`tipos_servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alarmas`.`tipos_servicio` (
  `tipo_servicio_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Identificador de la tabla Tipos_Servicio',
  `nombre_tipo_servicio` CHAR(128) NOT NULL COMMENT 'Nombre del Servicio. ',
  `observaciones_tipo_servicio` LONGTEXT NULL COMMENT 'Observaciones.',
  PRIMARY KEY (`tipo_servicio_id`))
COMMENT = 'Tabla que describe los tipos de servicio que provee la empresa. '
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `alarmas`.`detalle_ordenes_servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alarmas`.`detalle_ordenes_servicio` (
  `detalle_orden_servicio_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Identificador de la tabla ',
  `ordenes_servicio_orden_servicio_id` INT(11) UNSIGNED NOT NULL,
  `tipos_servicio_tipo_servicio_id` INT(11) UNSIGNED NOT NULL,
  `descripcion_detalle_orden_servicio` CHAR(128) NULL COMMENT 'descripcion del trabajo a realizar. ',
  PRIMARY KEY (`detalle_orden_servicio_id`),
  INDEX `Detalle_Ordenes_Servicio_FKIndex1` (`tipos_servicio_tipo_servicio_id` ASC),
  INDEX `Detalle_Ordenes_Servicio_FKIndex2` (`ordenes_servicio_orden_servicio_id` ASC),
  CONSTRAINT `fk_{5305367F-D8FA-492E-AE1A-E67E196BE98A}`
    FOREIGN KEY (`tipos_servicio_tipo_servicio_id`)
    REFERENCES `alarmas`.`tipos_servicio` (`tipo_servicio_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_{A42B40C4-0678-4F85-A4E6-4CEB459073A8}`
    FOREIGN KEY (`ordenes_servicio_orden_servicio_id`)
    REFERENCES `alarmas`.`ordenes_servicio` (`orden_servicio_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
